services:
  backend:
    command: >
      sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    environment:
      - DJANGO_ENV=staging
    volumes:
      - ./backend/.env.staging:/django/.env.staging

  nginx:
    volumes:
      - ./nginx/nginx/staging.conf:/etc/nginx/conf.d/default.conf
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"